# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d6ed0f7d8fccd4244f02f1befb2fdd22d3fffd2a5c901c369712dc89e272a27167f0e42cf186b6e70dd1442e52bf75281cf41fbaba58fff8624292061a7a34

test:
  secret_key_base: 352dc3c770c6b5ce7b3c23e94f5defc537aafe53f7a2b87d4b745b36e3cc056a3c73730db87ff831fd107cd1cda15b39cc75e3a253639c43c0c00361636fd893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
